Update to 20150301.

diff --git a/etc/security b/etc/security
--- a/etc/security
+++ b/etc/security
@@ -110,7 +110,591 @@ do
 	fi
 done
 
+<<<<<<< security
 ################################################################################
+=======
+# Root and uucp should both be in /etc/ftpusers.
+#
+if checkyesno check_ftpusers; then
+	list="uucp "$(awk '$2 == 0 { print $1 }' $MPBYUID)
+	for i in $list; do
+		if /usr/libexec/ftpd -C $i ; then
+			printf "\t$i is not denied\n"
+		fi
+	done > $OUTPUT
+	if [ -s $OUTPUT ]; then
+		printf "\nChecking the /etc/ftpusers configuration:\n"
+		cat $OUTPUT
+	fi
+fi
+
+# Uudecode should not be in the /etc/mail/aliases file.
+#
+if checkyesno check_aliases; then
+	for f in /etc/mail/aliases /etc/aliases; do
+		if [ -f $f ] && egrep '^[^#]*(uudecode|decode).*\|' $f; then
+			printf "\nEntry for uudecode in $f file.\n"
+		fi
+	done
+fi
+
+# Files that should not have + signs.
+#
+if checkyesno check_rhosts; then
+	list="/etc/hosts.equiv /etc/hosts.lpd"
+	for f in $list ; do
+		if [ -f $f ] && egrep '\+' $f > /dev/null ; then
+			printf "\nPlus sign in $f file.\n"
+		fi
+	done
+
+	# Check for special users with .rhosts files.  Only root and toor should
+	# have .rhosts files.  Also, .rhosts files should not have plus signs.
+	awk -F: '$1 != "root" && $1 != "toor" && \
+		($3 < 100 || $1 == "ftp" || $1 == "uucp") \
+			{ print $1 " " $9 }' $MP |
+	sort -k2 |
+	while read uid homedir; do
+		if [ -f ${homedir}/.rhosts ] ; then
+			rhost=$(ls -ldgT ${homedir}/.rhosts)
+			printf -- "$uid: $rhost\n"
+		fi
+	done > $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking for special users with .rhosts files.\n"
+		cat $OUTPUT
+	fi
+
+	while read uid homedir; do
+		if [ -f ${homedir}/.rhosts -a -r ${homedir}/.rhosts ] && \
+		    cat -f ${homedir}/.rhosts | egrep '\+' > /dev/null ; then
+			printf -- "$uid: + in .rhosts file.\n"
+		fi
+	done < $MPBYPATH > $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking .rhosts files syntax.\n"
+		cat $OUTPUT
+	fi
+fi
+
+# Check home directories.  Directories should not be owned by someone else
+# or writable.
+#
+if checkyesno check_homes; then
+	checkyesno check_homes_permit_usergroups && \
+		permit_usergroups=1 || permit_usergroups=0
+	while read uid homedir; do
+		if [ -d ${homedir}/ ] ; then
+			file=$(ls -ldgT ${homedir})
+			printf -- "$uid $file\n"
+		fi
+	done < $MPBYPATH |
+	awk -v "usergroups=$permit_usergroups" \
+	    -v "permit_owners_list=$check_homes_permit_other_owner"  '
+	     BEGIN {
+		split(permit_owners_list, a);
+		for (i in a) permit_owners[a[i]]++;
+	     }
+	     $1 != $4 && $4 != "root" && !permit_owners[$1] \
+		{ print "user " $1 " home directory is owned by " $4 }
+	     $2 ~ /^d....w/ && (!usergroups || $5 != $1) \
+		{ print "user " $1 " home directory is group writable" }
+	     $2 ~ /^d.......w/ \
+		{ print "user " $1 " home directory is other writable" }' \
+	    > $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking home directories.\n"
+		cat $OUTPUT
+	fi
+
+	# Files that should not be owned by someone else or readable.
+	list=".Xauthority .netrc .ssh/id_dsa .ssh/id_rsa .ssh/identity"
+	while read uid homedir; do
+		for f in $list ; do
+			file=${homedir}/${f}
+			if [ -f $file ] ; then
+				printf -- "$uid $f $(ls -ldgT $file)\n"
+			fi
+		done
+	done < $MPBYPATH |
+	awk -v "usergroups=$permit_usergroups" \
+	    -v "permit_owners_list=$check_homes_permit_other_owner"  '
+	     BEGIN {
+		split(permit_owners_list, a);
+		for (i in a) permit_owners[a[i]]++;
+	     }
+	     $1 != $5 && $5 != "root" && !permit_owners[$1] \
+		{ print "user " $1 " " $2 " file is owned by " $5 }
+	     $3 ~ /^-...r/ && (!usergroups || $6 != $1) \
+		{ print "user " $1 " " $2 " file is group readable" }
+	     $3 ~ /^-......r/ \
+		{ print "user " $1 " " $2 " file is other readable" }
+	     $3 ~ /^-....w/ && (!usergroups || $6 != $1) \
+		{ print "user " $1 " " $2 " file is group writable" }
+	     $3 ~ /^-.......w/ \
+		{ print "user " $1 " " $2 " file is other writable" }' \
+	    > $OUTPUT
+
+	# Files that should not be owned by someone else or writable.
+	list=".bash_history .bash_login .bash_logout .bash_profile .bashrc \
+	      .cshrc .emacs .exrc .forward .history .k5login .klogin .login \
+	      .logout .profile .qmail .rc_history .rhosts .shosts ssh .tcshrc \
+	      .twmrc .xinitrc .xsession .ssh/authorized_keys \
+	      .ssh/authorized_keys2 .ssh/config .ssh/id_dsa.pub \
+	      .ssh/id_rsa.pub .ssh/identity.pub .ssh/known_hosts \
+	      .ssh/known_hosts2"
+	while read uid homedir; do
+		for f in $list ; do
+			file=${homedir}/${f}
+			if [ -f $file ] ; then
+				printf -- "$uid $f $(ls -ldgT $file)\n"
+			fi
+		done
+	done < $MPBYPATH |
+	awk -v "usergroups=$permit_usergroups" \
+	    -v "permit_owners_list=$check_homes_permit_other_owner"  '
+	     BEGIN {
+		split(permit_owners_list, a);
+		for (i in a) permit_owners[a[i]]++;
+	     }
+	     $1 != $5 && $5 != "root" && !permit_owners[$1] \
+		{ print "user " $1 " " $2 " file is owned by " $5 }
+	     $3 ~ /^-....w/ && (!usergroups || $6 != $1) \
+		{ print "user " $1 " " $2 " file is group writable" }
+	     $3 ~ /^-.......w/ \
+		{ print "user " $1 " " $2 " file is other writable" }' \
+	    >> $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking dot files.\n"
+		cat $OUTPUT
+	fi
+fi
+
+# Mailboxes should be owned by user and unreadable.
+#
+if checkyesno check_varmail; then
+	ls -lA /var/mail | \
+	awk '	NR == 1 { next; }
+		$9 ~ /^\./ {next; }
+	    	$3 != $9 {
+			print "user " $9 " mailbox is owned by " $3
+		}
+		$1 != "-rw-------" {
+			print "user " $9 " mailbox is " $1 ", group " $4
+		}' > $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking mailbox ownership.\n"
+		cat $OUTPUT
+	fi
+fi
+
+# NFS exports shouldn't be globally exported
+#
+if checkyesno check_nfs && [ -f /etc/exports ]; then
+	awk '{
+		# ignore comments and blank lines
+		if ($0 ~ /^\#/ || $0 ~ /^$/ )
+			next;
+		# manage line continuation
+		while ($NF ~ /^\\$/) {
+			$NF = "";
+			line = $0 "";
+			getline;
+			$0 = line $0 "";
+		}
+
+		delete dir;
+		readonly = ndir = 0;
+		for (i = 1; i <= NF; ++i) {
+			if ($i ~ /^\//) dir[ndir++] = $i;
+			else if ($i ~ /^-/) {
+				if ($i ~ /^-(ro|o)$/) readonly = 1;
+				if ($i ~ /^-network/) next;
+			}
+			else next;
+		}
+		if (readonly)
+			for (item in dir)
+				rodir[nrodir++] = dir[item];
+		else
+			for (item in dir)
+				rwdir[nrwdir++] = dir[item];
+
+	}
+
+	END {
+		if (nrodir) {
+			printf("Globally exported file system%s, read-only:\n",
+				nrodir > 1 ? "s" : "");
+			for (item in rodir)
+				printf("\t%s\n", rodir[item]);
+		}
+		if (nrwdir) {
+			printf("Globally exported file system%s, read-write:\n",
+				nrwdir > 1 ? "s" : "");
+			for (item in rwdir)
+				printf("\t%s\n", rwdir[item]);
+		}
+	}' < /etc/exports > $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking for globally exported file systems.\n"
+		cat $OUTPUT
+	fi
+fi
+
+# Display any changes in setuid files and devices.
+#
+if checkyesno check_devices; then
+	> $ERR
+	(
+
+	# Convert check_devices_ignore_fstypes="foo !bar bax"
+	#    into "-fstype foo -o ! -fstype bar -o -fstype bax"
+	# and check_devices_ignore_paths="/foo !/bar /bax"
+	#    into " -path /foo -o ! -path /bar -o -path /bax"
+	#
+	ignexpr=$(\
+	    echo $check_devices_ignore_fstypes | \
+		sed -e's/\(!*\)\([^[:space:]]\{1,\}\)/-o \1 -fstype \2/g' ; \
+	    echo $check_devices_ignore_paths | \
+		sed -e's/\(!*\)\([^[:space:]]\{1,\}\)/-o \1 -path \2/g' \
+	)
+
+	# Massage the expression into ( $ignexpr ) -a -prune -o
+	if [ -n "${ignexpr}" ]; then
+		ignexpr=$(\
+			echo $ignexpr | \
+			    sed -e 's/^-o /( /' \
+				-e 's/$/ ) -a -prune -o/' \
+		)
+	fi
+
+	find / $ignexpr \
+	    \( \( -perm -u+s -a ! -type d \) -o \
+	       \( -perm -g+s -a ! -type d \) -o \
+	       -type b -o -type c \) -print0 | \
+	xargs -0 ls -ldgTq | sort +9 > $LIST
+
+	) 2> $OUTPUT
+
+	# Display any errors that occurred during system file walk.
+	if [ -s $OUTPUT ] ; then
+		printf "Setuid/device find errors:\n" >> $ERR
+		cat $OUTPUT >> $ERR
+		printf "\n" >> $ERR
+	fi
+
+	# Display any changes in the setuid file list.
+	egrep -v '^[bc]' $LIST > $TMP1
+	if [ -s $TMP1 ] ; then
+		# Check to make sure uudecode isn't setuid.
+		if grep -w uudecode $TMP1 > /dev/null ; then
+			printf "\nUudecode is setuid.\n" >> $ERR
+		fi
+
+		file=$work_dir/setuid
+		migrate_file "$backup_dir/setuid" "$file"
+		CUR=${file}.current
+		BACK=${file}.backup
+		if [ -s $CUR ] ; then
+			if cmp -s $CUR $TMP1 ; then
+				:
+			else
+				> $TMP2
+				join -110 -210 -v2 $CUR $TMP1 > $OUTPUT
+				if [ -s $OUTPUT ] ; then
+					printf "Setuid additions:\n" >> $ERR
+					tee -a $TMP2 < $OUTPUT >> $ERR
+					printf "\n" >> $ERR
+				fi
+
+				join -110 -210 -v1 $CUR $TMP1 > $OUTPUT
+				if [ -s $OUTPUT ] ; then
+					printf "Setuid deletions:\n" >> $ERR
+					tee -a $TMP2 < $OUTPUT >> $ERR
+					printf "\n" >> $ERR
+				fi
+
+				sort -k10 $TMP2 $CUR $TMP1 | \
+				    sed -e 's/[	 ][	 ]*/ /g' | \
+				    uniq -u > $OUTPUT
+				if [ -s $OUTPUT ] ; then
+					printf "Setuid changes:\n" >> $ERR
+					column -t $OUTPUT >> $ERR
+					printf "\n" >> $ERR
+				fi
+
+				backup_file update $TMP1 $CUR $BACK
+			fi
+		else
+			printf "Setuid additions:\n" >> $ERR
+			column -t $TMP1 >> $ERR
+			printf "\n" >> $ERR
+			backup_file add $TMP1 $CUR $BACK
+		fi
+	fi
+
+	# Check for block and character disk devices that are readable or
+	# writable or not owned by root.operator.
+	>$TMP1
+	DISKLIST="ccd ch hk hp ld md ra raid rb rd rl rx \
+	    sd se ss uk up vnd wd xd xy"
+#	DISKLIST="$DISKLIST ct mt st wt"
+	for i in $DISKLIST; do
+		egrep "^b.*/${i}[0-9][0-9]*[a-p]$"  $LIST >> $TMP1
+		egrep "^c.*/r${i}[0-9][0-9]*[a-p]$"  $LIST >> $TMP1
+	done
+
+	awk '$3 != "root" || $4 != "operator" || $1 !~ /.rw-r-----/ \
+		{ printf "Disk %s is user %s, group %s, permissions %s.\n", \
+		    $11, $3, $4, $1; }' < $TMP1 > $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking disk ownership and permissions.\n" >> $ERR
+		cat $OUTPUT >> $ERR
+		printf "\n" >> $ERR
+	fi
+
+	# Display any changes in the device file list.
+	egrep '^[bc]' $LIST | sort -k11 > $TMP1
+	if [ -s $TMP1 ] ; then
+		file=$work_dir/device
+		migrate_file "$backup_dir/device" "$file"
+		CUR=${file}.current
+		BACK=${file}.backup
+
+		if [ -s $CUR ] ; then
+			if cmp -s $CUR $TMP1 ; then
+				:
+			else
+				> $TMP2
+				join -111 -211 -v2 $CUR $TMP1 > $OUTPUT
+				if [ -s $OUTPUT ] ; then
+					printf "Device additions:\n" >> $ERR
+					tee -a $TMP2 < $OUTPUT >> $ERR
+					printf "\n" >> $ERR
+				fi
+
+				join -111 -211 -v1 $CUR $TMP1 > $OUTPUT
+				if [ -s $OUTPUT ] ; then
+					printf "Device deletions:\n" >> $ERR
+					tee -a $TMP2 < $OUTPUT >> $ERR
+					printf "\n" >> $ERR
+				fi
+
+				# Report any block device change. Ignore
+				# character devices, only the name is
+				# significant.
+				cat $TMP2 $CUR $TMP1 | \
+				    sed -e '/^c/d' | \
+				    sort -k11 | \
+				    sed -e 's/[	 ][	 ]*/ /g' | \
+				    uniq -u > $OUTPUT
+				if [ -s $OUTPUT ] ; then
+					printf "Block device changes:\n" >> $ERR
+					column -t $OUTPUT >> $ERR
+					printf "\n" >> $ERR
+				fi
+
+				backup_file update $TMP1 $CUR $BACK
+			fi
+		else
+			printf "Device additions:\n" >> $ERR
+			column -t $TMP1 >> $ERR
+			printf "\n" >> $ERR
+			backup_file add $TMP1 $CUR $BACK >> $ERR
+		fi
+	fi
+	if [ -s $ERR ] ; then
+		printf "\nChecking setuid files and devices:\n"
+		cat $ERR
+		printf "\n"
+	fi
+fi
+
+# Check special files.
+# Check system binaries.
+#
+# Create the mtree tree specifications using:
+#	mtree -cx -pDIR -kmd5,uid,gid,mode,nlink,size,link,time > DIR.secure
+#	chown root:wheel DIR.secure
+#	chmod u+r,go= DIR.secure
+#
+# Note, this is not complete protection against Trojan horsed binaries, as
+# the hacker can modify the tree specification to match the replaced binary.
+# For details on really protecting yourself against modified binaries, see
+# the mtree(8) manual page.
+#
+if checkyesno check_mtree; then
+	if checkyesno check_mtree_follow_symlinks; then
+		check_mtree_flags="-L"
+	else
+		check_mtree_flags=""
+	fi
+	mtree -e -l -p / $check_mtree_flags -f $SPECIALSPEC 3>&1 >$OUTPUT 2>&3 |
+		grep -v '^mtree: dev/tty: Device not configured$' >&2
+	if [ -s $OUTPUT ]; then
+		printf "\nChecking special files and directories.\n"
+		cat $OUTPUT
+	fi
+
+	for file in /etc/mtree/*.secure; do
+		[ $file = '/etc/mtree/*.secure' ] && continue
+		tree=$(sed -n -e '3s/.* //p' -e 3q $file)
+		mtree $check_mtree_flags -f $file -p $tree > $TMP1
+		if [ -s $TMP1 ]; then
+			printf "\nChecking $tree:\n"
+			cat $TMP1
+		fi
+	done > $OUTPUT
+	if [ -s $OUTPUT ]; then
+		printf "\nChecking system binaries:\n"
+		cat $OUTPUT
+	fi
+fi
+
+# Backup disklabels of available disks
+#
+if checkyesno check_disklabels; then
+		# migrate old disklabels
+	for file in $(ls -1d $backup_dir/$backup_dir/disklabel.* \
+	    $backup_dir/disklabel.* 2>/dev/null); do
+		migrate_file "$file" "$work_dir/${file##*/}"
+	done
+
+		# generate list of old disklabels, fdisks & wedges,
+		# and remove them
+	ls -1d $work_dir/disklabel.* $work_dir/fdisk.* $work_dir/wedges.* \
+	    2>/dev/null |
+	    egrep -v '\.(backup|current)(,v)?$' > $LABELS
+	xargs rm < $LABELS
+
+	disks="$(iostat -x | cut -f 1 -d ' ' )"
+
+		# generate disklabels of all disks excluding:	cd fd md dk st
+		# nfs and "device" (the header of iostat)
+	for i in $disks; do
+		case $i in
+		[cfm]d[0-9]*|dk[0-9]*|st[0-9]*|nfs[0-9]*|device)
+			;;
+		*)
+			if disklabel $i > /dev/null 1>&2; then
+				disklabel $i > "$work_dir/disklabel.$i"
+			fi
+			;;
+		esac
+	done
+
+		# if fdisk is available, generate fdisks for:	ed ld sd wd
+	if [ -x /sbin/fdisk ]; then
+		for i in $disks; do
+			case $i in
+			[elsw]d[0-9]*)
+				/sbin/fdisk $i > "$work_dir/fdisk.$i" \
+				    2>/dev/null
+				;;
+			esac
+		done
+	fi
+
+		# if dkctl is available, generate dkctl listwedges
+		# for:	ed ld sd wd cgd ofdisk ra rl raid
+	if [ -x /sbin/dkctl ]; then
+		for i in $disks; do
+			case $i in
+			[elsw]d[0-9]*|cgd[0-9]*|ofdisk[0-9]*|r[al][0-9]*|raid[0-9]*)
+				if /sbin/dkctl $i listwedges -qe; then
+					/sbin/dkctl $i listwedges \
+					    > "$work_dir/wedges.$i" 2>/dev/null
+				fi
+				;;
+			esac
+		done
+	fi
+
+		# append list of new disklabels, fdisks and wedges
+	ls -1d $work_dir/disklabel.* $work_dir/fdisk.* $work_dir/wedges.* \
+	    2>/dev/null |
+	    egrep -v '\.(backup|current)(,v)?$' >> $LABELS
+	CHANGELIST="$LABELS $CHANGELIST"
+fi
+
+if checkyesno check_lvm; then
+		# generate list of existing LVM elements Physical Volumes,
+		# Volume Groups and Logical Volumes.
+	if [ -x /sbin/lvm ]; then
+		lvm pvdisplay -m >"$work_dir/lvm.pv" 2>/dev/null
+		lvm vgdisplay -m >"$work_dir/lvm.vg" 2>/dev/null
+		lvm lvdisplay -m >"$work_dir/lvm.lv" 2>/dev/null
+	fi
+	ls -1d $work_dir/lvm.* 2>/dev/null |
+	    egrep -v '\.(backup|current)(,v)?$'>> $LVM_LABELS
+	CHANGELIST="$CHANGELIST $LVM_LABELS"
+fi
+
+# Check for changes in the list of installed pkgs
+#
+if checkyesno check_pkgs && have_pkgs; then
+	pkgs=$work_dir/pkgs
+	migrate_file "$backup_dir/pkgs" "$pkgs"
+	pkg_dbdir=$(${pkg_admin} config-var PKG_DBDIR)
+	: ${pkg_dbdir:=/var/db/pkg}
+	(	cd $pkg_dbdir
+		$pkg_info | sort
+		echo ""
+		find . \( -name +REQUIRED_BY -o -name +CONTENTS \) -print0 |
+			xargs -0 ls -ldgTq | sort -t. +1 | sed -e 's, \./, ,'
+	 ) > $pkgs
+	echo "$pkgs" > $PKGS
+	CHANGELIST="$PKGS $CHANGELIST"
+fi
+
+# List of files that get backed up and checked for any modifications.
+# Any changes cause the files to rotate.
+#
+if checkyesno check_changelist ; then
+	mtree -D -k type -f $SPECIALSPEC -E exclude |
+	    sed '/^type=file/!d ; s/type=file \.//' | unvis > $CHANGEFILES
+
+	(
+		# Add other files which might dynamically exist:
+		#	/etc/ifconfig.*
+		#	/etc/raid*.conf
+		#	/etc/rc.d/*
+		#	/etc/rc.conf.d/*
+		#
+		echo "/etc/ifconfig.*"
+		echo "/etc/raid*.conf"
+		echo "/etc/rc.d/*"
+		echo "/etc/rc.conf.d/*"
+		echo "/etc/lvm/backup/*"
+		echo "/etc/lvm/archive/*"
+
+		# Add /etc/changelist
+		#
+		if [ -s /etc/changelist ]; then
+			grep -v '^#' /etc/changelist
+		fi
+	) | while read file; do
+		case "$file" in
+		*[\*\?\[]*)	# If changelist line is a glob ...
+				# ... expand possible backup files
+				#
+			ls -1d $(echo $backup_dir/${file}.current) 2>/dev/null \
+			    | sed "s,^$backup_dir/,, ; s,\.current$,,"
+
+				# ... expand possible files
+				#
+			ls -1d $(echo $file) 2>/dev/null
+			;;
+		*)
+				# Otherwise, just print the filename
+			echo $file
+			;;
+		esac
+	done >> $CHANGEFILES
+	CHANGELIST="$CHANGEFILES $CHANGELIST"
+fi
+>>>>>>> 1.119
 
 # Special case backups, including the master password file and
 # ssh private host keys. The normal backup mechanisms for
